from django import forms
from django.forms import Form

class SkorFormR16(Form):
    skor_a = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_b = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_c = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_d = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_e = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_f = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_g = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_h = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_i = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_j = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_k = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_l = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_m = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_n = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_o = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_p = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_q = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_r = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_s = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_t = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_u = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_v = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_w = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_x = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_y = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_z = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_aa = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_ab = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_ac = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_ad = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_ae = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_af = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))


class SkorFormR16(Form):
    skor_a = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_b = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_c = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_d = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_e = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_f = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_g = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_h = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_i = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_j = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_k = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_l = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_m = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_n = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_o = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_p = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))


class SkorFormQuarter(Form):
    skor_a = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_b = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_c = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_d = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_e = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_f = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_g = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_h = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))

class SkorFormSemi(Form):
    skor_a = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_b = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_c = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-c', 'placeholder': '0'}))
    skor_d = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-d', 'placeholder': '0'}))

class SkorFormFinal(Form):
    skor_a3 = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_b3 = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
    skor_a = forms.IntegerField(label='skor-b', widget=forms.NumberInput(
        attrs={'id': 'skor-a', 'placeholder': '0'}))
    skor_b = forms.IntegerField(label='skor-a', widget=forms.NumberInput(
        attrs={'id': 'skor-b', 'placeholder': '0'}))
